### ISSUE TITLE
show pending and publish post

### ISSUE THREAD

**Issue by tourscaner** [WebDevStudios/WDS-Multisite-Aggregate#12]
hello
How can I show in admin 
pending and publish post
by WDS-Multisite-Aggregate
thanks

<a href="http://tashrifatavazeh.com">تشریفات مجالس</a>

**Comment by tw2113** [comment]
Show this information where?

**Comment by tourscaner** [comment]
hi
Show in  wp-admin
I've replaced all publish word to pending at wds-multisite-aggregate.php
it worked but show only pending post
i want pending and publish post

**Comment by tw2113** [comment]
if you can point out what lines you changed, I can better help you. Chances are you should be passing an array of both 'pending' and 'publish' to get both, but I can't say for certain.

**Comment by tourscaner** [comment]
i Change this line:
https://github.com/WebDevStudios/WDS-Multisite-Aggregate/blob/master/wds-multisite-aggregate.php#L409
 to:
`if ( 'pending' == $post->post_status ) {`

**Comment by tw2113** [comment]
That line would just need to be changed to:

```
if ( 'publish' == $post->post_status || 'pending' == $post->post_status ) {
```

**Comment by tourscaner** [comment]
thanks Michael this is ok.
other question
now how can i set this for custom post type?

**Comment by tw2113** [comment]
Unless I'm mistaken, this is going to run on all of them, as per https://github.com/WebDevStudios/WDS-Multisite-Aggregate/blob/master/wds-multisite-aggregate.php#L79. Last I knew, save_post ran on all of them.

Closing as there's not really an issue going on at the moment.
