### ISSUE TITLE
Does this copy featured images?

### ISSUE THREAD

**Issue by Darthmaul** [WebDevStudios/WDS-Multisite-Aggregate#15]
I selected the option to copy thumbnails and it doesn't seem to copy them.

Am I doing something wrong?

Andrew

**Comment by tw2113** [comment]
See this thread about how featured images are handled: https://github.com/WebDevStudios/WDS-Multisite-Aggregate/issues/5

**Comment by Darthmaul** [comment]
Could this be solved with a shared media library plugin? It seems right now the issue is the fact that the url is trying to reference an image that isn't in the current site's media library.

**Comment by tw2113** [comment]
Personally unsure, as I've never done anything with a shared library plugin, and I have to believe our plugin here wasn't coded to take that into consideration.

It's worth a shot to see what that does, but it may still require some customizations to work as expected.

**Comment by Darthmaul** [comment]
Shared library plugins seem to exclude featured images :(
