### ISSUE TITLE
removal of featured image not synced

### ISSUE THREAD

**Issue by streiten** [WebDevStudios/WDS-Multisite-Aggregate#8]
updating a network site posts featured image works fine. 
but looks like removing it leaves the post_meta rows for the thumbnail and thus still displaying the featured image on the aggregated blog. 

around https://github.com/WebDevStudios/WDS-Multisite-Aggregate/blob/master/wds-multisite-aggregate.php#L310 ? or any other pointers where to start.

**Comment by tw2113** [comment]
So to clarify, we'll use this example.

You've sync'd and aggregated everything into a site. Then you update and remove the featured image from one of the sites that gets compiled, and re-sync. The aggregated site retains the featured image, despite the original source having successfully removed the featured image?

**Comment by streiten** [comment]
Hmm. Re-sync happens on post save after featured image removal on a networksite that is aggregated onto the main site and is not refelected there. so maybe in other words it's direction original to cloned post.

**Comment by streiten** [comment]
resolved with #16 and #18
